"""Non-element nodes in a document body.

Found by the fidelity lab on Apache POI's `Bug66263-table.docx`: a real
document whose body contains an XML comment crashed the parser outright with

    AttributeError: '_cython_3_2_4.cython_function_or_method'
                    object has no attribute 'rsplit'

because `parse_blocks` assumed every child of `w:body` is an element and did
`child.tag.rsplit("}", 1)`. lxml gives comments and processing instructions a
*callable* tag, not a string.

An unhandled AttributeError is the one outcome the product contract rules out:
the result must be a proven pass or a labelled status, never a crash.
"""
from zipfile import ZIP_DEFLATED, ZipFile

import pytest

from word_replica.parser.parser import DocxParser

CT_XML = (
    b'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    b'<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    b'<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument'
    b'.wordprocessingml.document.main+xml"/>'
    b"</Types>"
)
RELS_XML = (
    b'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    b'<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships'
    b'/officeDocument" Target="word/document.xml"/>'
    b"</Relationships>"
)
_DOC = (
    '<?xml version="1.0"?><w:document '
    'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
    "<w:body>{}</w:body></w:document>"
)


def _docx(path, body_xml: str):
    with ZipFile(path, "w", ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", CT_XML)
        archive.writestr("_rels/.rels", RELS_XML)
        archive.writestr("word/document.xml", _DOC.format(body_xml).encode("utf-8"))
    return path


_PARAGRAPH = "<w:p><w:r><w:t>text</w:t></w:r></w:p>"


@pytest.mark.parametrize(
    "name, body",
    [
        ("comment before content", "<!-- generated by something --> " + _PARAGRAPH),
        ("comment after content", _PARAGRAPH + "<!-- trailing -->"),
        ("comment between paragraphs", _PARAGRAPH + "<!-- middle -->" + _PARAGRAPH),
        ("processing instruction", "<?custom directive?>" + _PARAGRAPH),
        ("only a comment", "<!-- nothing else at all -->"),
    ],
)
def test_a_non_element_node_in_the_body_does_not_crash_the_parser(tmp_path, name, body):
    model = DocxParser().parse(_docx(tmp_path / "doc.docx", body))

    assert isinstance(model.body, list)


def test_content_around_a_comment_is_still_parsed(tmp_path):
    model = DocxParser().parse(
        _docx(tmp_path / "doc.docx", _PARAGRAPH + "<!-- middle -->" + _PARAGRAPH)
    )

    assert model.plain_text().count("text") == 2


def test_the_real_apache_poi_document_parses(tmp_path):
    # The document that found this. Kept as a synthetic reconstruction rather
    # than a committed binary: the shape that matters is a commented body.
    body = "<!--[if gte mso 9]><![endif]-->" + _PARAGRAPH + "<w:sectPr/>"

    model = DocxParser().parse(_docx(tmp_path / "poi.docx", body))

    assert model.plain_text().strip() == "text"
